import { DataGridFilter } from "rcl-shared-components";
export const DataGridMuiEdit = () => {
  const rows = [
    {
      flag: "0",
      pod: "THLKR",
      pot1: "",
      pot2: "",
      del: "0",
      vsl: "CAN",
      ton: "",
      bookingTeu: "100",
      id: "1",
      polTerminalCode: "SGSIN/SGKPT",
      seq: "1",
      polTerminal: "THLCH/THHLT",
      svc: "RLI33",
      voy: "016W",
      "45hc": "0",
      "20rf": "0",
      bsaTeu: "100",
      bookingEta: "2,000",
      "40rf": "0",
      "40hc": "0",
      "20gp": "0",
      teus: "",
      "40gp": "0",
      bsaEta: "2,000",
      primaryKey: "THLKR-RLI22",
    },
    {
      flag: "0",
      pod: "THLKR",
      pot1: "",
      pot2: "",
      del: "0",
      vsl: "CAN",
      ton: "",
      bookingTeu: "100",
      id: "2",
      polTerminalCode: "SGSIN/SGKPT",
      seq: "1",
      polTerminal: "THLCH/THHLT",
      svc: "RLI",
      voy: "016W",
      "45hc": "0",
      "20rf": "0",
      bsaTeu: "100",
      bookingEta: "2,000",
      "40rf": "0",
      "40hc": "0",
      "20gp": "0",
      teus: "",
      "40gp": "0",
      bsaEta: "2,000",
      primaryKey: "MYNMA-RLI",
    },
    {
      flag: "1",
      pod: "CNSHA",
      pot1: "HKHKG",
      pot2: "",
      del: "1",
      vsl: "MSK",
      ton: "320",
      bookingTeu: "150",
      id: "3",
      polTerminalCode: "JPNGO/JPTYO",
      seq: "1",
      polTerminal: "JPNGO/JPTYO",
      svc: "JPX22",
      voy: "078E",
      "45hc": "2",
      "20rf": "1",
      bsaTeu: "180",
      bookingEta: "3,500",
      "40rf": "1",
      "40hc": "3",
      "20gp": "4",
      teus: "22",
      "40gp": "3",
      bsaEta: "4,200",
      primaryKey: "CNSHA-JPX22",
    },
    {
      flag: "0",
      pod: "KRPUS",
      pot1: "TWKHH",
      pot2: "CNSHK",
      del: "1",
      vsl: "ONE",
      ton: "240",
      bookingTeu: "120",
      id: "4",
      polTerminalCode: "JPTYO/JPOSA",
      seq: "1",
      polTerminal: "Tokyo/Osaka",
      svc: "KRX12",
      voy: "045W",
      "45hc": "0",
      "20rf": "2",
      bsaTeu: "150",
      bookingEta: "2,800",
      "40rf": "1",
      "40hc": "2",
      "20gp": "3",
      teus: "15",
      "40gp": "2",
      bsaEta: "3,100",
      primaryKey: "KRPUS-KRX12",
    },
    {
      flag: "1",
      pod: "VNHPH",
      pot1: "",
      pot2: "",
      del: "0",
      vsl: "COSCO",
      ton: "180",
      bookingTeu: "90",
      id: "5",
      polTerminalCode: "CNNGB/CNSHA",
      seq: "1",
      polTerminal: "Ningbo/Shanghai",
      svc: "VNX08",
      voy: "112S",
      "45hc": "0",
      "20rf": "1",
      bsaTeu: "110",
      bookingEta: "2,200",
      "40rf": "0",
      "40hc": "1",
      "20gp": "2",
      teus: "8",
      "40gp": "2",
      bsaEta: "2,500",
      primaryKey: "VNHPH-VNX08",
    },
    {
      flag: "0",
      pod: "SGSIN",
      pot1: "MYPKG",
      pot2: "",
      del: "2",
      vsl: "EVER",
      ton: "430",
      bookingTeu: "220",
      id: "6",
      polTerminalCode: "IDTPP/IDJKT",
      seq: "1",
      polTerminal: "Tanjung Priok/Jakarta",
      svc: "SGX19",
      voy: "089E",
      "45hc": "3",
      "20rf": "2",
      bsaTeu: "250",
      bookingEta: "4,800",
      "40rf": "2",
      "40hc": "4",
      "20gp": "5",
      teus: "30",
      "40gp": "4",
      bsaEta: "5,200",
      primaryKey: "SGSIN-SGX19",
    },
    {
      flag: "1",
      pod: "AUPKL",
      pot1: "NZAKL",
      pot2: "",
      del: "1",
      vsl: "APL",
      ton: "520",
      bookingTeu: "270",
      id: "7",
      polTerminalCode: "AUSYD/AUMEL",
      seq: "1",
      polTerminal: "Sydney/Melbourne",
      svc: "ANZ14",
      voy: "056S",
      "45hc": "2",
      "20rf": "3",
      bsaTeu: "290",
      bookingEta: "5,600",
      "40rf": "3",
      "40hc": "5",
      "20gp": "6",
      teus: "38",
      "40gp": "5",
      bsaEta: "6,100",
      primaryKey: "AUPKL-ANZ14",
    },
    {
      flag: "0",
      pod: "USNYC",
      pot1: "USPNW",
      pot2: "USMIA",
      del: "2",
      vsl: "YML",
      ton: "680",
      bookingTeu: "350",
      id: "8",
      polTerminalCode: "CNSHA/CNDLC",
      seq: "1",
      polTerminal: "Shanghai/Dalian",
      svc: "USX25",
      voy: "124W",
      "45hc": "4",
      "20rf": "3",
      bsaTeu: "380",
      bookingEta: "7,200",
      "40rf": "4",
      "40hc": "6",
      "20gp": "7",
      teus: "48",
      "40gp": "6",
      bsaEta: "7,800",
      primaryKey: "USNYC-USX25",
    },
    {
      flag: "1",
      pod: "PHMNL",
      pot1: "",
      pot2: "",
      del: "0",
      vsl: "OOCL",
      ton: "210",
      bookingTeu: "110",
      id: "9",
      polTerminalCode: "HKHKG/TWKHH",
      seq: "1",
      polTerminal: "Hong Kong/Kaohsiung",
      svc: "PHX06",
      voy: "077S",
      "45hc": "1",
      "20rf": "1",
      bsaTeu: "130",
      bookingEta: "2,500",
      "40rf": "1",
      "40hc": "2",
      "20gp": "3",
      teus: "12",
      "40gp": "1",
      bsaEta: "2,800",
      primaryKey: "PHMNL-PHX06",
    },
    {
      flag: "0",
      pod: "MXZLO",
      pot1: "USLAX",
      pot2: "",
      del: "1",
      vsl: "CMA",
      ton: "450",
      bookingTeu: "230",
      id: "10",
      polTerminalCode: "CNSHA/CNTSN",
      seq: "1",
      polTerminal: "Shanghai/Tianjin",
      svc: "MXX11",
      voy: "098W",
      "45hc": "2",
      "20rf": "2",
      bsaTeu: "260",
      bookingEta: "5,100",
      "40rf": "2",
      "40hc": "4",
      "20gp": "5",
      teus: "32",
      "40gp": "5",
      bsaEta: "5,500",
      primaryKey: "MXZLO-MXX11",
    },
    {
      flag: "1",
      pod: "AEDXB",
      pot1: "OMMCT",
      pot2: "",
      del: "1",
      vsl: "HMM",
      ton: "380",
      bookingTeu: "190",
      id: "11",
      polTerminalCode: "INBOM/INJNR",
      seq: "1",
      polTerminal: "Mumbai/Nhava Sheva",
      svc: "MEX17",
      voy: "066E",
      "45hc": "1",
      "20rf": "2",
      bsaTeu: "210",
      bookingEta: "4,100",
      "40rf": "2",
      "40hc": "3",
      "20gp": "4",
      teus: "24",
      "40gp": "4",
      bsaEta: "4,400",
      primaryKey: "AEDXB-MEX17",
    },
    {
      flag: "0",
      pod: "DEHAM",
      pot1: "NLRTM",
      pot2: "GBSOU",
      del: "2",
      vsl: "MSC",
      ton: "590",
      bookingTeu: "300",
      id: "12",
      polTerminalCode: "ESBCN/FRMRS",
      seq: "1",
      polTerminal: "Barcelona/Marseille",
      svc: "EUR03",
      voy: "112N",
      "45hc": "3",
      "20rf": "2",
      bsaTeu: "330",
      bookingEta: "6,400",
      "40rf": "3",
      "40hc": "5",
      "20gp": "6",
      teus: "40",
      "40gp": "6",
      bsaEta: "6,900",
      primaryKey: "DEHAM-EUR03",
    },
  ];

  const columns = [
    {
      field: "svc",
      headerName: "Service",
      width: 100,
      hideable: false, //EXAMPLE : If you want the field to always be displayed and cannot be hidden.
      editable: false, //EXAMPLE : If you are in edit mode but want some fields to not be editable, use editable false.
    },
    {
      field: "pod",
      headerName: "POD",
      width: 150,
      // EXAMPLE : If you want to connect data or calculate together, you can use valueGetter
      // valueGetter: (value: any, row: any) => {
      //   return `${row.vsl || ''} ${row.voy || ''}`;
      // },
    },
    { field: "polTerminal", headerName: "POL Terminal", width: 150 },
    { field: "pot1", headerName: "POT1", width: 80 },
    { field: "pot2", headerName: "POT2", width: 80 },
    { field: "polTerminalCode", headerName: "POL Terminal Code", width: 150 },
    { field: "del", headerName: "DEL", width: 70 },
    { field: "vsl", headerName: "Vessel", width: 100 },
    { field: "voy", headerName: "Voyage", width: 100 },
    { field: "flag", headerName: "Flag", width: 70 },
    { field: "bsaTeu", headerName: "BSA TEU", width: 100 },
    { field: "bsaEta", headerName: "BSA ETA", width: 100 },
    { field: "bookingTeu", headerName: "Booking TEU", width: 120 },
    { field: "bookingEta", headerName: "Booking ETA", width: 120 },
    { field: "20gp", headerName: "20GP", width: 80 },
    { field: "40gp", headerName: "40GP", width: 80 },
    { field: "40hc", headerName: "40HC", width: 80 },
    { field: "45hc", headerName: "45HC", width: 80 },
    { field: "20rf", headerName: "20RF", width: 80 },
    { field: "40rf", headerName: "40RF", width: 80 },
    { field: "teus", headerName: "TEUs", width: 80 },
    { field: "ton", headerName: "TON", width: 80 },
  ];
  const columnGroupingModel = [
    {
      groupId: "BSA",
      children: [{ field: "bsaTeu" }, { field: "bsaEta" }],
    },
    {
      groupId: "Booking",
      children: [{ field: "bookingTeu" }, { field: "bookingEta" }],
    },
    {
      groupId: "Laden (Forecast)",
      children: [
        { field: "20gp" },
        { field: "40gp" },
        { field: "40hc" },
        { field: "45hc" },
        { field: "20rf" },
        { field: "40rf" },
        { field: "teus" },
        { field: "ton" },
      ],
    },
  ];

  const handleSelectedValue = (newRow: any, oldRow: any) => {
    console.log(newRow, "newRow");
    console.log(oldRow, "oldRow");
    return newRow;
  };

  return (
    <>
      <DataGridFilter
        showToolbar
        showGroupToolbarButton
        multiFilterToolbar
        rows={rows}
        columns={columns}
        columnGroupingModel={columnGroupingModel}
        editMode
        onRowUpdate={handleSelectedValue}
        initialState={
          {
            // pagination: { paginationModel: { pageSize: 3 } },
          }
        }
        // pageSizeOptions={[3, 6, 9, 12, 15]}
        sx={{
          "& .MuiDataGrid-root": {
            border: "0 !important;",
            boxShadow: "none !important;"
          },

        }}
      />
    </>
  );
};
